# Generated by Django 5.2.6 on 2025-10-15 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('file_type', models.CharField(choices=[('python', 'Python'), ('airtest', 'Airtest')], max_length=10, verbose_name='文件类型')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('status', models.CharField(choices=[('available', '可用'), ('unavailable', '不可用'), ('processing', '处理中')], default='processing', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-upload_time'],
            },
        ),
    ]
