# Generated by Django 5.2.6 on 2025-10-15 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('devices', models.JSONField(verbose_name='设备列表')),
                ('app_file', models.CharField(max_length=500, verbose_name='应用文件路径')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TaskDeviceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='设备ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_results', to='tasks.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务设备结果',
                'verbose_name_plural': '任务设备结果',
                'ordering': ['device_id'],
            },
        ),
    ]
